- op: replace
  path: /spec/generators/0/git/files/0/path
  value: applicationsets/all/apps/dev/*.yaml

- op: replace
  path: /spec/generators/0/git/revision
  value: users/will

- op: replace
  path: /spec/template/spec/source/targetRevision
  value: users/will