---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
   headerStyle: boxed
   layout:
    Infrastructure:
      style: row
      columns: 3
  bookmarks.yaml: |
    - Repositories:
        - Github:
            - abbr: GH
              href: https://github.com/
        - Ansible:
          - href: https://github.com/TheWill10m/ansible
        - ArgoCD:
          - href: https://github.com/TheWill10m/argocd
        - Docker:
          - href: https://github.com/TheWill10m/docker
  services.yaml: |
    - Infrastructure:
        - Proxmox:
            href: https://mortis.wdalgleish.com:8006/
            description: Mortis PVE
        - TrueNAS:
            href: https://nas.wdalgleish.com/
            description: TrueNAS Core
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: false
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
