---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  namespace: argocd
  labels:
    name: awxn-operator
spec:
  project: default

  source:
    chart: awx-operator
    repoURL: https://ansible-community.github.io/awx-operator-helm
    targetRevision: v2.19.0

  destination:
    server: https://kubernetes.default.svc
    namespace: awx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argocd
  labels:
    name: awx
spec:
  project: default

  source:
    repoURL: https://github.com/thewill10m/argocd
    targetRevision: main
    path: apps/awx

  destination:
    server: https://kubernetes.default.svc
    namespace: awx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
