---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  labels:
    name: homepage
spec:
  project: default

  source:
    repoURL: https://github.com/thewill10m/argocd
    targetRevision: main
    path: apps/homepage

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
