---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  labels:
    name: longhorn
spec:
  project: default

  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.6.0
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
    - repoURL: https://github.com/thewill10m/argocd
      targetRevision: main
      path: apps/longhorn

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
