---
apiVersion: v2
name: awx-operator
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: awx-operator
    version: 1.3.0
    repository: https://ansible-community.github.io/awx-operator-helm